#make file example

CC = gcc #compiler
CFLAGS = -Wall -std=c99 #-O3
TARGET = tester #target file name

all:
	$(CC) $(CFLAGS) TESTA_ISTO_SFF_PROJETO_FINAL_ALFA.c -o $(TARGET) oraculo.o

clean:
	rm $(TARGET)
