#make file example

CC = gcc #compiler
CFLAGS = -Wall -std=c99 -O3
TARGET = proj #target file name

all:
	$(CC) $(CFLAGS) projeto_final.c -o $(TARGET) key.o files.o mode.o oraculo.o intermedio.o

clean:
	rm $(TARGET)
